
all:
	gcc -Wall -ansi -pedantic -o leaves leaves.c -lgpr -lm -lz -fopenmp

debug:
	gcc -Wall -ansi -pedantic -g -o leaves leaves.c -lgpr -lm -lz -fopenmp

clean:
	rm -f *.o leaves species* agent.c server.rb *.png *.dot
