
all:
	gcc -Wall -ansi -pedantic -o violentcrime violentcrime.c -lgpr -lm -lz -fopenmp

debug:
	gcc -Wall -ansi -pedantic -g -o violentcrime violentcrime.c -lgpr -lm -lz -fopenmp

clean:
	rm -f *.o violentcrime agent agent.c server.rb *.png *.dot
