
all:
	gcc -Wall -ansi -pedantic -o arrhythmia arrhythmia.c -lgpr -lm -fopenmp

debug:
	gcc -Wall -ansi -pedantic -g -o arrhythmia arrhythmia.c -lgpr -lm -fopenmp

clean:
	rm -f *.o arrhythmia agent agent.c *.rb
