
all:
	gcc -Wall -ansi -pedantic -o cancer cancer.c -lgpr -lm -lz -fopenmp

debug:
	gcc -Wall -ansi -pedantic -g -o cancer cancer.c -lgpr -lm -lz -fopenmp

clean:
	rm -f *.o *.png cancer agent agent.c server.rb
