
all:
	gcc -Wall -ansi -pedantic -o art art.c -lgpr -lm -lz -fopenmp

debug:
	gcc -Wall -ansi -pedantic -g -o atr atr.c -lgpr -lm -lz -fopenmp

clean:
	rm -f *.o art agent agent.c server.rb *.png *.dot
